[project]
name = "audiblez"
version = "0.1.12"
description = "Generate audiobooks from e-books (epub to wav/m4b)"
authors = [
    { name = "Claudio Santini", email = "hireclaudio@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.9,<3.13" # librosa/llvmlite have no support for python > 3.12
dependencies = [
    "bs4 (==0.0.2)",
    "attrs (==24.3.0)",
    "audioread (==3.0.1)",
    "babel (==2.16.0)",
    "beautifulsoup4 (==4.12.3)",
    "bibtexparser (==2.0.0b8)",
    "certifi (==2024.12.14)",
    "cffi (==1.17.1)",
    "charset-normalizer (==3.4.1)",
    "clldutils (==3.24.0)",
    "colorama (==0.4.6)",
    "coloredlogs (==15.0.1)",
    "colorlog (==6.9.0)",
    "csvw (==3.5.1)",
    "decorator (==5.1.1)",
    "dlinfo (==1.2.1)",
    "ebooklib (==0.18)",
    "espeakng-loader (==0.2.1)",
    "flatbuffers (==24.12.23)",
    "humanfriendly (==10.0)",
    "idna (==3.10)",
    "isodate (==0.7.2)",
    "joblib (==1.4.2)",
    "jsonschema (==4.23.0)",
    "jsonschema-specifications (==2024.10.1)",
    "kokoro-onnx (==0.2.6)",
    "language-tags (==1.2.0)",
    "lazy-loader (==0.4)",
    "librosa (==0.10.2.post1)",
    "llvmlite (==0.43.0)",
    "lxml (==5.3.0)",
    "markdown (==3.7)",
    "markupsafe (==3.0.2)",
    "mpmath (==1.3.0)",
    "msgpack (==1.1.0)",
    "numba (==0.60.0)",
    "numpy (==2.0.2)",
    "onnxruntime (==1.20.1)",
    "packaging (==24.2)",
    "phonemizer-fork (==3.3.1)",
    "platformdirs (==4.3.6)",
    "pooch (==1.8.2)",
    "protobuf (==5.29.3)",
    "pycparser (==2.22)",
    "pylatexenc (==2.10)",
    "pyparsing (==3.2.1)",
    "python-dateutil (==2.9.0.post0)",
    "rdflib (==7.1.2)",
    "referencing (==0.35.1)",
    "regex (==2024.11.6)",
    "requests (==2.32.3)",
    "rfc3986 (==1.5.0)",
    "rpds-py (==0.22.3)",
    "scikit-learn (==1.6.1)",
    "scipy (==1.15.1)",
    "segments (==2.2.1)",
    "six (==1.17.0)",
    "soundfile (==0.13.0)",
    "soupsieve (==2.6)",
    "soxr (==0.5.0.post1)",
    "sympy (==1.13.3)",
    "tabulate (==0.9.0)",
    "threadpoolctl (==3.5.0)",
    "typing-extensions (==4.12.2)",
    "uritemplate (==4.1.1)",
    "urllib3 (==2.3.0)",
    "pydub (>=0.25.1,<0.26.0)",
    "pick (>=2.4.0,<3.0.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[project.urls]
Homepage = "https://claudio.uk/posts/epub-to-audiobook.html"
Documentation = "https://github.com/santinic/audiblez"
Repository = "https://github.com/santinic/audiblez"
Issues = "https://github.com/santinic/audiblez/issues"

[project.scripts]
audiblez = "audiblez:cli_main"
